### ISSUE TITLE
Update dependancies

### ISSUE THREAD

**Issue by neb0lle** [acmpesuecc/dablob#1]
### Update dependancies without breaking anything.
- Update all dependancies to its latest version in the `package.json` file

**Comment by Shresht-Ahuja** [comment]
can i get assign to this pls

**Comment by neb0lle** [comment]
!assign @Shresht-Ahuja

**Comment by neb0lle** [comment]
!extend 60

**Comment by Shresht-Ahuja** [comment]
can i get re-assigned

**Comment by neb0lle** [comment]
!assign @Shresht-Ahuja

**Comment by bwaklog** [comment]
!deassign
